# Generated by Django 2.0 on 2021-11-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0002_auto_20211129_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugerenciavoto',
            name='titulo',
            field=models.CharField(max_length=50, verbose_name='Título'),
        ),
    ]
