# Generated by Django 2.0 on 2021-11-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0003_auto_20211129_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugerenciavoto',
            name='campos_preguntas',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
