# Generated by Django 2.0 on 2021-11-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0004_auto_20211129_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugerenciavoto',
            name='campos_preguntas',
            field=models.PositiveSmallIntegerField(default='2'),
        ),
    ]
