# Generated by Django 2.0 on 2021-11-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0005_auto_20211129_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sugerencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('suggesting_date', models.DateField()),
                ('content', models.TextField()),
                ('send_date', models.DateField()),
                ('is_approved', models.NullBooleanField()),
            ],
        ),
    ]
