# Generated by Django 2.0 on 2021-12-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0006_sugerencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugerencia',
            name='content',
            field=models.TextField(max_length=4000),
        ),
    ]
