# Generated by Django 2.0 on 2021-12-19 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0007_auto_20211219_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugerencia',
            name='suggesting_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
