# Generated by Django 2.0 on 2021-12-26 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0008_auto_20211219_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sugerenciavoto',
            name='preguntas',
        ),
        migrations.AlterField(
            model_name='sugerencia',
            name='send_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='sugerencia',
            name='suggesting_date',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='Pregunta',
        ),
        migrations.DeleteModel(
            name='SugerenciaVoto',
        ),
    ]
